version: '2'
services:
  service1:
    build: ./service
    image: go-service1
    ports:
      - 8001:8000
  service2:
    build: ./service
    image: go-service2
    ports:
      - 8002:8000
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"